// Group #8, CS 440, Fall 2023

// asian_menu.dart
// asian food
// https://www.recipetineats.com/

class AsianMenu {
  final Map<String, Map<String, String>> dishesWithRecipes = {
    'Bok Choy in Ginger Sauce': {
      'recipe': 'Bok Choy in Ginger Sauce is a quick and delightful way to enjoy Asian greens. This dish cooks in minutes, ensuring the bok choy retains its crunch. Serve it as a side or over noodles in soup!\n'
        'Prep: 3 minutes\nCook: 3 minutes\nTotal: 6 minutes\n\n'
        'Ingredients:\n'
        '6 small bok choy or other Asian greens\n'
        '2 tbsp vegetable oil\n'
        '1/4 cup ginger (or 1 tbsp garlic), finely julienned\n'
        '1/4 cup water\n\n'
        'Sauce:\n'
        '3 tsp cornflour/cornstarch\n'
        '1 1/2 tsp light soy sauce (or all-purpose soy)\n'
        '1 tsp oyster sauce (or substitute vegetarian oyster sauce)\n'
        '2 tsp Chinese cooking wine\n'
        '1 tsp toasted sesame oil\n'
        '1/4 cup water\n'
        '1/4 tsp cooking salt\n'
        'Pinch of white pepper\n\n'
        'Instructions:\n'
        '1. Trim the base of the bok choy and separate the leaves. Leave baby bok choy intact and '
        'cut large stems in half lengthwise. Rinse and shake off excess water.\n'
        '2. In a jug, mix the sauce ingredients (excluding water) until smooth, then add water.\n'
        '3. Sauté ginger (or garlic) in oil until slightly golden and floppy. Add bok choy and toss for 15 seconds.\n'
        '4. Steam for 45 seconds, then pour in the sauce and toss for 30 seconds until it thickens. Bok choy should be tender but still crisp. If the sauce gets too thick, add a splash of water.\n'
        '5. Serve your Bok Choy in Ginger Sauce hot and enjoy!',

      'image': 'https://www.recipetineats.com/wp-content/uploads/2023/09/Bok-choy-with-ginger-sauce_7.jpg',
    },

    'Pad Thai': {
        'recipe': 'Pad Thai is a quick and delicious stir-fried noodle dish you can make at home.'
        ' Its a Thai favorite with a perfect balance of sweet, salty, and tangy flavors. You can use chicken or your choice of protein. Serve with lime wedges and optional chili for that authentic Thai touch!\n'
        'Prep: 20 minutes\nCook: 10 minutes\nTotal: 30 minutes\n'
        'Servings: 2-3 people\n\n'
        'Ingredients:\n'
        '125g (4oz) dried rice sticks (Pad Thai noodles)\n'
        'Sauce:\n'
        '1 1/2 tbsp tamarind puree\n'
        '3 tbsp brown sugar\n'
        '2 tbsp fish sauce\n'
        '1 1/2 tbsp oyster sauce\n'
        'Stir Fry:\n'
        '2-3 tbsp vegetable or canola oil\n'
        '1/2 onion, sliced\n'
        '2 garlic cloves, finely chopped\n'
        '150g (5oz) chicken breast or thigh, thinly sliced\n'
        '2 eggs, lightly whisked\n'
        '1 1/2 cups of bean sprouts\n'
        '1/2 cup firm tofu, cut into batons\n'
        '1/4 cup garlic chives, cut into pieces\n'
        '1/4 cup finely chopped peanuts\n'
        'For Serving:\n'
        'Lime wedges (essential)\n'
        'Ground chili or cayenne pepper (optional)\n'
        'Extra bean sprouts\n'
        '\nInstructions:\n'
        '1. Soak noodles in boiling water for 5 minutes, then drain and rinse under cold water. Don’t let them sit for more than 5-10 minutes.\n'
        '2. Mix the sauce ingredients in a small bowl.\n'
        '3. Heat oil in a large pan over high heat. Add garlic and onion, cook for 30 seconds.\n'
        '4. Add chicken and cook until mostly done, about 1 1/2 minutes.\n'
        '5. Push chicken to one side, pour beaten eggs on the other side. Scramble, then mix into the chicken.\n'
        '6. Add bean sprouts, tofu, noodles, and sauce. Toss for about 1 1/2 minutes until the sauce is absorbed by the noodles.\n'
        '7. Add garlic chives and half the peanuts. Toss quickly and remove from heat.\n'
        '8. Serve immediately, topped with remaining peanuts and lime wedges. '
        'Sprinkle with chili and extra bean sprouts on the side if desired. Squeeze lime juice to taste before eating.',
    'image': 'https://www.recipetineats.com/wp-content/uploads/2020/01/Chicken-Pad-Thai_9-SQ.jpg',
  },
    'Spring Rolls':{

    'recipe': 'Make crispy, golden Spring Rolls at home that are far better than takeout! These rolls have a delightful filling and a shatteringly crisp exterior. Enjoy the homemade taste!\n'
        'Prep: 20 minutes\nCook: 10 minutes\nTotal: 30 minutes\n'
        'Servings: 15-20\n\n'
        'Ingredients:\n'
        'Filling:\n'
        '1 tbsp oil\n'
        '2 garlic cloves, finely chopped or minced\n'
        '400g (13oz) pork mince (or chicken or turkey)\n'
        '6 dried shiitake mushrooms (soaked in boiling water) or 8 fresh\n'
        '1 1/2 cups shredded carrot\n'
        '1 1/2 cups bean sprouts\n'
        '1 1/2 cups shredded green cabbage\n'
        '1 tsp cornflour/cornstarch\n'
        '1 1/2 tbsp Oyster Sauce\n'
        '2 tsp soy sauce (light or all-purpose)\n'
        'Spring Rolls:\n'
        '15-20 spring roll wrappers (8" squares) or 35-40 small spring roll wrappers (Note 2)\n'
        '2 tsp cornflour (for sealing rolls)\n'
        '1 tbsp water (for sealing rolls)\n'
        'Oil for frying (vegetable) or oil spray for baking (canola)\n'
        'Sweet and Sour Sauce (makes ~2/3 cup):\n'
        '2 tsp cornflour/cornstarch\n'
        '2 tbsp water\n'
        '1/2 cup apple cider vinegar\n'
        '1/3 cup brown sugar (adjust to taste)\n'
        '2 tbsp tomato ketchup\n'
        '2 tsp soy sauce\n'
        '\nInstructions:\n'
        '1. Cook the filling by stir-frying garlic, meat, vegetables, and seasonings. Ensure the filling is not watery.\n'
        '2. Cool the filling (quickly in the fridge for 5 minutes).\n'
        '3. Mix cornflour and water for sealing the rolls.\n'
        '4. Place spring roll wrapper smooth side down. Add a spoon of filling and roll, sealing with cornflour sludge.\n'
        '5. Heat oil in a pan, then deep fry the spring rolls until deep golden, about 1 1/2 - 2 minutes.\n'
        '6. Drain on paper towels and serve hot with Sweet and Sour Sauce!',
      'image': 'https://www.cubesnjuliennes.com/wp-content/uploads/2021/01/Spring-Roll-Recipe.jpg',
    },

    'Vegetarian Chow Mein': {
      'recipe':'Enjoy this delicious vegetarian/vegan version of chow mein. It closely resembles the traditional version but uses tofu instead of meat and a sauce without oyster sauce. You can make the sauce from scratch or use my Real Chinese All Purpose Stir Fry Sauce (Vegetarian version) for a quicker preparation.\n'
        'Prep: 10 minutes\nCook: 5 minutes\nTotal: 15 minutes\n'
        'Servings: 2\n\n'
        'Ingredients:\n'
        '6 oz (180g) fresh chow mein noodles\n'
        '2 tbsp oil\n'
        '2 garlic cloves, minced\n'
        '2 cups shredded Chinese cabbage\n'
        '1/2 cup carrot, julienned\n'
        '2 scallion/shallot stems, cut into 2" pieces\n'
        '1 cup bean sprouts\n'
        '\nTofu and marinade:\n'
        '5 oz (150g) firm tofu, sliced\n'
        '1/2 tbsp soy sauce\n'
        '1 tbsp Chinese cooking wine\n'
        '\nSauce:\n'
        '1/2 tbsp hoisin sauce\n'
        '1 1/2 tbsp soy sauce\n'
        '1/2 tbsp chili garlic sauce or sriracha (optional)\n'
        '2 tsp sugar\n'
        '1/2 tsp sesame oil\n'
        '1/4 cup water\n'
        'White pepper\n'
        '\nInstructions:\n'
        '1. Prepare noodles as per packet instructions (usually soaking in boiling water).\n'
        '2. Combine tofu with marinade and set aside for 5 minutes.\n'
        '3. Combine sauce ingredients in a small bowl.\n'
        '4. Heat oil in a wok over high heat, add garlic and stir-fry for 10 seconds.\n'
        '5. Add tofu and stir-fry until it caramelizes, about 1 minute. Be gentle with the tofu.\n'
        '6. Add cabbage and carrot, stir-fry until the cabbage starts to wilt.\n'
        '7. Add noodles, scallions/shallots, bean sprouts, and sauce. Stir-fry until the noodles are warmed through and coated with the sauce, about 1 minute. '
        'Do not overcook; the bean sprouts should remain crisp.\n'
        '8. Serve immediately.\n\n'
        'Directions using homemade Real Chinese All Purpose Stir Fry Sauce:\n'
        '- If you have homemade Real Chinese All Purpose Stir Fry Sauce, skip the marinade and sauce steps.\n'
        '- Substitute the tofu marinade with 1 tbsp Stir Fry Sauce.\n'
        '- Substitute the Sauce ingredients with 1/4 cup Stir Fry Sauce and 1/4 cup water.',
    'image': 'https://choosingchia.com/jessh-jessh/uploads/2021/09/Vegan-chow-mein-9.jpg',
  },
    'Bibimbap': {
      'recipe': 'Bibimbap is a delightful Korean dish with plenty of flavors. It is simple to make and does not require a lot of effort.'
        ' Perfect for a satisfying meal!\n'
        'Prep: 40 minutes\nCook: 30 minutes\nTotal: 1 hour 10 minutes\n'
        'Servings: 4\n\n'
        'Ingredients:\n'
        '4 cups cooked white rice\n'
        '4 eggs\n'
        '2 tsp sesame seeds\n'
        'Korean Beef & Marinade:\n'
        '250g beef tenderloin or thick steak, very finely sliced\n'
        '1/4 green apple, grated\n'
        '3 garlic cloves, minced\n'
        '1 tbsp soy sauce\n'
        '1 tbsp honey\n'
        '2 tsp sesame oil\n'
        'Vegetables:\n'
        '2 carrots, cut into batons\n'
        '2 zucchini, cut into batons\n'
        '1 bunch of spinach\n'
        '8 dried shiitake mushrooms\n'
        '4 cups bean sprouts\n'
        '2 tsp garlic, minced\n'
        '8 tsp vegetable oil, separated\n'
        '1/2 tsp salt\n'
        '1.5 tsp soy sauce\n'
        '1/4 tsp fish sauce\n'
        'Sesame oil\n'
        'Bibimbap Sauce:\n'
        '4 tbsp gochujang paste\n'
        '2 tbsp mirin\n'
        '2 tbsp rice vinegar\n'
        '1.5 tsp soy sauce\n'
        '3 tsp white sugar\n'
        '1 garlic clove, finely grated\n'
        '2.5 tsp sesame oil\n'
        '\nInstructions:\n'
        '1. Prepare Bibimbap Sauce by mixing ingredients until sugar is dissolved.\n'
        '2. Marinate beef for 30 minutes or overnight.\n'
        '3. Cook marinated beef in a skillet until cooked with caramelized bits.\n'
        '4. Prepare vegetables, including shiitake, carrot, zucchini, spinach, and bean sprouts.\n'
        '5. Cook each vegetable separately, then set aside to cool.\n'
        '6. Fry eggs in a skillet to your taste.\n'
        '7. Place warm rice in bowls, top with cooked vegetables and beef. Add a fried egg on top.\n'
        '8. Sprinkle with sesame seeds, drizzle with sesame oil, and serve with Bibimbap Sauce!',
      'image': 'https://peaktoplate.com/wp-content/uploads/2022/06/pronghorn-bibimbap-in-bowl-with-chopsticks.jpg',
    },

    'Wonton Soup': {
      'recipe': 'Wonton Soup is a delightful Chinese dish that is easy to make. You can enjoy homemade wontons filled with real ingredients in a flavorful broth.\n'
        'Prep: 20 minutes\nCook: 15 minutes\nTotal: 35 minutes\n'
        'Servings: Makes 50 wontons (approximately 2 servings)\n\n'
        'Ingredients:\n'
        '50 - 60 wonton wrappers\n'
        'Wonton Filling:\n'
        '200g lean pork mince\n'
        '200g peeled prawns/shrimp, roughly chopped\n'
        '1 tbsp ginger, finely grated\n'
        '2 shallots/green onions, finely chopped\n'
        '1 tbsp light soy sauce\n'
        '2 tbsp Chinese cooking wine\n'
        '1/2 tsp salt\n'
        '2 tbsp toasted sesame oil\n'
        'Broth (for 2 servings):\n'
        '3 cups chicken broth\n'
        '2 garlic cloves, smashed\n'
        '1 cm piece of ginger, sliced\n'
        '1.5 tbsp light soy sauce\n'
        '2 tsp sugar\n'
        '1.5 tbsp Chinese cooking wine\n'
        '1/4 - 1/2 tsp sesame oil\n'
        'To Serve:\n'
        'Shallots/scallions, finely chopped\n'
        'Bok choy or Chinese broccoli (optional)\n'
        'Dried egg noodles (optional)\n'
        '\nInstructions:\n'
        '1. Combine filling ingredients in a bowl and mash until fairly smooth.\n'
        '2. Wrap the wontons according to your preference (My Way or Asian Grocery Store Way).\n'
        '3. Cook the wontons for 4 minutes in boiling water, then remove and place in serving bowls.\n'
        '4. Prepare the broth by simmering the broth ingredients for 5-10 minutes.\n'
        '5. If using vegetables, blanch them in the soup broth and place them in serving bowls.\n'
        '6. Prepare noodles if using and place them in serving bowls with cooked wontons and vegetables.\n'
        '7. Ladle the soup over the ingredients and serve!',
    'image': 'https://redhousespice.com/wp-content/uploads/2022/07/chinese-pork-wonton-in-soup.jpg',
  },

    'Vietnamese Pho':{
      'recipe': 'Experience the magic of one of the greatest soups in the world with this easy-to-follow traditional recipe!\n'
        'Prep: 20 minutes\nCook: 3 hours\nTotal: 3 hours 20 minutes\n'
        'Servings: 6\n\n'
        'Ingredients:\n'
        'Aromatics:\n'
        '2 large onions, halved\n'
        '150g (5oz) ginger, sliced down the center\n'
        'Spices:\n'
        '10 star anise\n'
        '4 cinnamon quills\n'
        '4 cardamom pods\n'
        '3 cloves\n'
        '1.5 tbsp coriander seeds\n'
        'Beef bones (Note 1):\n'
        '1.5kg (3lb) beef brisket\n'
        '1kg (2lb) meaty beef bones\n'
        '1kg (2lb) marrow bones (leg, knuckle), cut to reveal marrow\n'
        '3.5 liters (3.75 quarts) water (15 cups)\n'
        'Seasoning:\n'
        '2 tbsp white sugar\n'
        '1 tbsp salt\n'
        '40 ml (3 tbsp) fish sauce (Note 2)\n'
        'Noodle Soup - PER BOWL:\n'
        '50g (1.5oz) dried rice sticks (or 120g/4oz fresh) (Note 3)\n'
        '30g (1oz) beef tenderloin, raw, very thinly sliced (Note 4)\n'
        '3-5 brisket slices (used for broth)\n'
        'Toppings:\n'
        'Beansprouts, handful\n'
        'Thai basil, 3-5 sprigs\n'
        'Coriander/cilantro, 3-5 sprigs (or more basil)\n'
        'Lime wedges\n'
        'Finely sliced red chili\n'
        'Hoisin sauce\n'
        'Sriracha (for spiciness)\n'
        '\nInstructions:\n'
        '1. Char onion and ginger in a hot skillet. Set aside.\n'
        '2. Lightly toast spices in a dry skillet for 3 minutes.\n'
        '3. Rinse bones and brisket, then cover with water in a large stockpot. '
        'Boil for 5 minutes, then drain. Rinse each bone and brisket under tap water.\n'
        '4. In a clean pot, bring 3.5 liters of water to a boil. Add bones, onion, ginger, spices, sugar, and salt. '
        'Cover and simmer for 3 hours.\n'
        '5. Remove brisket, refrigerate. Simmer remaining soup uncovered for 40 minutes. Strain and adjust seasoning.\n'
        '6. Prepare rice noodles. Place noodles in a bowl, top with raw beef and brisket. Ladle over hot broth to cook the beef. '
        'Serve with toppings on the side!',
  'image': 'https://leitesculinaria.com/wp-content/uploads/2016/06/pho-recipe.jpg',
},

    'Kimchi Fried Rice': {
      'recipe': 'Kimchi Fried Rice is a staple in every Korean household. It\'s a typical way to use up leftover rice and kimchi, while still delivering big flavors that belie its humble nature. Along with kimchi, gochujang (Korean chili paste) is the other hero ingredient that brings flavor, color, and heat to the party!\n'
        'Prep: 10 minutes\nCook: 6 minutes\nTotal: 16 minutes\n'
        'Servings: 4 - 5 as a side\n\n'
        'Ingredients:\n'
        '2 tsp sesame oil, toasted, separated (1 tsp + 1 tsp)\n'
        '2 garlic cloves, finely chopped\n'
        '200g/7oz enoki mushrooms (Note 1)\n'
        '1 tbsp oil, vegetable, peanut or canola\n'
        '1 tbsp gochujang (Korean chili paste, Note 2)\n'
        '1 cup (packed) kimchi (Note 3)\n'
        '1/4 cup kimchi juice, from the kimchi above (Note 3)\n'
        '3 cups cooked, day-old white rice (Note 4)\n'
        '\nGarnishes:\n'
        'Fried egg, runny yolk, sunny-side up\n'
        'Black sesame seeds\n'
        'Green onions, finely sliced\n'
        'Crispy seaweed strips (Note 5)\n'
        'Instructions:\n'
        '1. Strain kimchi juice – Place kimchi in a sieve set over a bowl. Press firmly to extract as much juice as you can. We need juice for the sauce, and to reduce the wetness of the kimchi so it does not make the rice soggy.\n'
        '2. Measure kimchi juice – Measure out 3 tablespoons of the kimchi juice and set aside. (Note 3 if you are short).\n'
        '3. Cook enoki mushrooms – Heat 1 tsp sesame oil in a large non-stick pan over medium-high heat. Add enoki mushrooms, about 1/2 tsp garlic, plus a pinch of salt and pepper. Cook for 1 1/2 minutes until just-wilted, then remove to a plate.\n'
        '4. Garlic and gochujang – Return the pan to the stove. Add oil. Add garlic and cook for 20 seconds until it is lightly golden. Add gochujang and cook for 30 seconds until it dries out a bit – just move it around in a lump, breaking it up a bit as you can.\n'
        '5. Cook kimchi – Add kimchi and cook for 1 minute, just to heat it through (kimchi does not need to be cooked) and drive off any excess moisture.\n'
        '6. Add rice and kimchi juice – Add rice and kimchi juice, toss well for 1 1/2 minutes until the rice is fully stained red. Toss well to ensure the gochujang mixed with the kimchi disperses throughout the rice.\n'
        '7. Enoki mushrooms and 1 tsp sesame oil – Add the enoki mushrooms and remaining 1 teaspoon of sesame oil. Toss through rice.\n'
        '8. Serve, topped with garnishes of choice!\n',
  'image': 'https://www.recipetineats.com/wp-content/uploads/2021/03/Kimchi-Fried-Rice-Skillet.jpg',
  },



  };

  AsianMenu();
}
